package activitytracker; 

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class Home extends JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        icon = new javax.swing.JPanel();
        JDailyLabel = new javax.swing.JLabel();
        jFriendsLabel = new javax.swing.JLabel();
        jFriendsLabel1 = new javax.swing.JLabel();
        JRunLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        distUnit = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        totalDistLabel = new javax.swing.JLabel();
        totalTimeLabel = new javax.swing.JLabel();
        averageIncliLabel = new javax.swing.JLabel();
        timeUnit = new javax.swing.JLabel();
        incliUnit = new javax.swing.JLabel();
        distLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        incliLabel = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        prettyThing = new javax.swing.JPanel();
        recentPanel = new javax.swing.JPanel();
        runDataTable = new javax.swing.JTable();
        recentTitleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarPanel.setBackground(new java.awt.Color(255, 255, 255));
        sidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout iconLayout = new javax.swing.GroupLayout(icon);
        icon.setLayout(iconLayout);
        iconLayout.setHorizontalGroup(
            iconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        iconLayout.setVerticalGroup(
            iconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        sidebarPanel.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 190, 160));

        JDailyLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JDailyLabel.setForeground(new java.awt.Color(96, 83, 150));
        JDailyLabel.setText("Daily Challenges");
        JDailyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JDailyLabelMouseClicked(evt);
            }
        });
        sidebarPanel.add(JDailyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jFriendsLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jFriendsLabel.setForeground(new java.awt.Color(96, 83, 150));
        jFriendsLabel.setText("Friends");
        jFriendsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFriendsLabelMouseClicked(evt);
            }
        });
        sidebarPanel.add(jFriendsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, 24));

        jFriendsLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jFriendsLabel1.setForeground(new java.awt.Color(96, 83, 150));
        jFriendsLabel1.setText("Friends");
        jFriendsLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFriendsLabel1MouseClicked(evt);
            }
        });
        sidebarPanel.add(jFriendsLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, 24));

        JRunLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        JRunLabel.setForeground(new java.awt.Color(96, 83, 150));
        JRunLabel.setText("Detailed Run Statistics");
        JRunLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JRunLabelMouseClicked(evt);
            }
        });
        sidebarPanel.add(JRunLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        getContentPane().add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 490));

        mainPanel.setBackground(new java.awt.Color(247, 247, 247));
        mainPanel.setPreferredSize(new java.awt.Dimension(780, 200));
        mainPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mainPanelMouseDragged(evt);
            }
        });
        mainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainPanelMousePressed(evt);
            }
        });
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(96, 83, 150));
        title.setText("Welcome to Activity Tracker");
        mainPanel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 23, 270, 37));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        distUnit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        distUnit.setForeground(new java.awt.Color(96, 83, 150));
        distUnit.setText("km");

        jPanel11.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        totalDistLabel.setText("//to-do");

        totalTimeLabel.setText("//to-do");

        averageIncliLabel.setText("//to-do");

        timeUnit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        timeUnit.setForeground(new java.awt.Color(96, 83, 150));
        timeUnit.setText("hours:mins");

        incliUnit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        incliUnit.setForeground(new java.awt.Color(96, 83, 150));
        incliUnit.setText("m");

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalDistLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(distUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeUnit))
                .addGap(75, 75, 75)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(incliUnit)
                    .addComponent(averageIncliLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalDistLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(averageIncliLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incliUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mainPanel.add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 530, -1));

        distLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        distLabel.setForeground(new java.awt.Color(96, 83, 150));
        distLabel.setText("Total Distances Covered");
        mainPanel.add(distLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 102, 140, 41));

        timeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(96, 83, 150));
        timeLabel.setText("Total Time Ran");
        mainPanel.add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 102, 124, 41));

        incliLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        incliLabel.setForeground(new java.awt.Color(96, 83, 150));
        incliLabel.setText("Average Inclination");
        mainPanel.add(incliLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 106, 124, 30));

        btn_close.setBackground(new java.awt.Color(96, 83, 150));
        btn_close.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_close.setForeground(new java.awt.Color(255, 255, 255));
        btn_close.setText("X");
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        mainPanel.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 20, 30));

        prettyThing.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout prettyThingLayout = new javax.swing.GroupLayout(prettyThing);
        prettyThing.setLayout(prettyThingLayout);
        prettyThingLayout.setHorizontalGroup(
            prettyThingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        prettyThingLayout.setVerticalGroup(
            prettyThingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        mainPanel.add(prettyThing, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 180, -1));

        runDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        recentTitleLabel.setText("Your Recent Runs");

        javax.swing.GroupLayout recentPanelLayout = new javax.swing.GroupLayout(recentPanel);
        recentPanel.setLayout(recentPanelLayout);
        recentPanelLayout.setHorizontalGroup(
            recentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recentPanelLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(runDataTable, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(recentPanelLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(recentTitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        recentPanelLayout.setVerticalGroup(
            recentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recentPanelLayout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(recentTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(runDataTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        mainPanel.add(recentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 520, 140));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 780, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMouseClicked(MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void mainPanelMousePressed(MouseEvent evt) {//GEN-FIRST:event_mainPanelMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_mainPanelMousePressed

    private void mainPanelMouseDragged(MouseEvent evt) {//GEN-FIRST:event_mainPanelMouseDragged
        // TODO add your handling code here:
         int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_mainPanelMouseDragged

    //MouseListener for friends panel
    private void jFriendsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFriendsLabelMouseClicked
        JFriendsFrame friendframe = new JFriendsFrame();
        friendframe.setVisible(true);
        friendframe.pack();
        friendframe.setLocationRelativeTo(null);
        friendframe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        
    }//GEN-LAST:event_jFriendsLabelMouseClicked

    //MouseListener for daily challenges
    private void JDailyLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JDailyLabelMouseClicked
        JDailyChallengesFrame dailyFrame = new JDailyChallengesFrame();
        dailyFrame.setVisible(true);
        dailyFrame.pack();
        dailyFrame.setLocationRelativeTo(null);
        dailyFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        
    }//GEN-LAST:event_JDailyLabelMouseClicked

    //Cant delete use VSCODE!
    private void jFriendsLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFriendsLabel1MouseClicked
     
    }//GEN-LAST:event_jFriendsLabel1MouseClicked

    //MouseListener to go to run panel
    private void JRunLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JRunLabelMouseClicked
        JRunFrame runframe = new JRunFrame();
        runframe.setVisible(true);
        runframe.pack();
        runframe.setLocationRelativeTo(null);
        runframe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();   
    }//GEN-LAST:event_JRunLabelMouseClicked

    int xx ,xy;
    
       
    //bad idea
    
    
    private void onClick(JPanel panel)
    {
        panel.setBackground(new Color(205, 136, 205));
    }
    
     private void onLeaveClick(JPanel panel)
    {
        panel.setBackground(Color.white);
    }
    
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JDailyLabel;
    private javax.swing.JLabel JRunLabel;
    private javax.swing.JLabel averageIncliLabel;
    private javax.swing.JLabel btn_close;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel distLabel;
    private javax.swing.JLabel distUnit;
    private javax.swing.JPanel icon;
    private javax.swing.JLabel incliLabel;
    private javax.swing.JLabel incliUnit;
    private javax.swing.JLabel jFriendsLabel;
    private javax.swing.JLabel jFriendsLabel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel prettyThing;
    private javax.swing.JPanel recentPanel;
    private javax.swing.JLabel recentTitleLabel;
    private javax.swing.JTable runDataTable;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel timeUnit;
    private javax.swing.JLabel title;
    private javax.swing.JLabel totalDistLabel;
    private javax.swing.JLabel totalTimeLabel;
    // End of variables declaration//GEN-END:variables

}
