package activitytracker;

import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.text.NumberFormat;
import javax.swing.*;

import activitytracker.data.CsvImporter;

public class Home extends JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        JDailyLabel = new javax.swing.JLabel();
        jFriendsLabel = new javax.swing.JLabel();
        jFriendsLabel1 = new javax.swing.JLabel();
        JRunLabel = new javax.swing.JLabel();
        jIconLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        distUnit = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        totalDistLabel = new javax.swing.JLabel();
        totalTimeLabel = new javax.swing.JLabel();
        averageIncliLabel = new javax.swing.JLabel();
        timeUnit = new javax.swing.JLabel();
        incliUnit = new javax.swing.JLabel();
        distLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        incliLabel = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        prettyThing = new javax.swing.JPanel();
        recentPanel = new javax.swing.JPanel();
        JRecentDisplayLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
//        recentRunsTable = new javax.swing.JTable();
        jImportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarPanel.setBackground(new java.awt.Color(255, 255, 255));
        sidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JDailyLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JDailyLabel.setForeground(new java.awt.Color(96, 83, 150));
        JDailyLabel.setText("Daily Challenges");
        JDailyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JDailyLabelMouseClicked(evt);
            }
        });
        sidebarPanel.add(JDailyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jFriendsLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jFriendsLabel.setForeground(new java.awt.Color(96, 83, 150));
        jFriendsLabel.setText("Friends");
        jFriendsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFriendsLabelMouseClicked(evt);
            }
        });
        sidebarPanel.add(jFriendsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, 24));

        jFriendsLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jFriendsLabel1.setForeground(new java.awt.Color(96, 83, 150));
        jFriendsLabel1.setText("Friends");
        jFriendsLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFriendsLabel1MouseClicked(evt);
            }
        });
        sidebarPanel.add(jFriendsLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, 24));

        JRunLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        JRunLabel.setForeground(new java.awt.Color(96, 83, 150));
        JRunLabel.setText("Detailed Run Statistics");
        JRunLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JRunLabelMouseClicked(evt);
            }
        });
        sidebarPanel.add(JRunLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/activitytracker/Images/index.png"))); // NOI18N
        jIconLabel.setText("");
        sidebarPanel.add(jIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 190, 160));

        getContentPane().add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 510));

        mainPanel.setBackground(new java.awt.Color(247, 247, 247));
        mainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.darkGray));
        mainPanel.setPreferredSize(new java.awt.Dimension(780, 200));
        mainPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mainPanelMouseDragged(evt);
            }
        });
        mainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainPanelMousePressed(evt);
            }
        });
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(96, 83, 150));
        title.setText("Welcome to Activity Tracker");
        mainPanel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 23, 270, 37));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        distUnit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        distUnit.setForeground(new java.awt.Color(96, 83, 150));
        distUnit.setText("m");

        jPanel11.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        ClassData[] data = Singleton.loadedProfile.getRunDatas();
        double totalDist = 0;
        double totalTime = 0;
        double averageIncli = 0;

        totalDistLabel.setText("0");
        totalTimeLabel.setText("0");
        averageIncliLabel.setText("0");

        if (data!= null) {
            for (ClassData run : data) {
                totalDist += run.getDistance();
                totalTime += run.getDuration();
                averageIncli += run.getAltitude();
            }

            averageIncli /= data.length;

            String totalDistStr = NumberFormat.getInstance().format(totalDist);
            String averageIncliStr = NumberFormat.getInstance().format(averageIncli);
            int hours = (int) totalTime / 3600;
            double remainder = (double) totalTime - hours * 3600;
            int mins = (int) remainder / 60;

            totalDistLabel.setText(totalDistStr);
            totalTimeLabel.setText(String.valueOf(hours) + "h " + String.valueOf(mins) + "m");
            averageIncliLabel.setText(averageIncliStr);
        }

        timeUnit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        timeUnit.setForeground(new java.awt.Color(96, 83, 150));
        timeUnit.setText("hours:mins");

        incliUnit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        incliUnit.setForeground(new java.awt.Color(96, 83, 150));
        incliUnit.setText("m");

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalDistLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(distUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeUnit))
                .addGap(75, 75, 75)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(incliUnit)
                    .addComponent(averageIncliLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalDistLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(averageIncliLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incliUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(343, 343, 343))
        );

        mainPanel.add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 530, 110));

        distLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        distLabel.setForeground(new java.awt.Color(96, 83, 150));
        distLabel.setText("Total Distances Covered");
        mainPanel.add(distLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 102, 140, 41));

        timeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(96, 83, 150));
        timeLabel.setText("Total Time Ran");
        mainPanel.add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 102, 124, 41));

        incliLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        incliLabel.setForeground(new java.awt.Color(96, 83, 150));
        incliLabel.setText("Average Inclination");
        mainPanel.add(incliLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 106, 124, 30));

        btn_close.setBackground(new java.awt.Color(96, 83, 150));
        btn_close.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_close.setForeground(new java.awt.Color(255, 255, 255));
        btn_close.setText("X");
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        mainPanel.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 20, 30));

        prettyThing.setBackground(new java.awt.Color(96, 83, 150));
        prettyThing.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout prettyThingLayout = new javax.swing.GroupLayout(prettyThing);
        prettyThing.setLayout(prettyThingLayout);
        prettyThingLayout.setHorizontalGroup(
            prettyThingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        prettyThingLayout.setVerticalGroup(
            prettyThingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        mainPanel.add(prettyThing, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 180, -1));

        JRecentDisplayLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JRecentDisplayLabel.setForeground(new java.awt.Color(96, 83, 150));
        JRecentDisplayLabel.setText("Recent Runs");

        Object[][] tableData = {
                {"Empty!","Empty!","Empty!","Empty!"},
                {"Empty!","Empty!","Empty!","Empty!"}};

        if (data != null) {
            int ite = data.length-1;
            tableData = new Object[3][4];
            for (int i = 0; i < 3; i++) {
                tableData[i][0] = data[ite].getFormattedDate();
                tableData[i][1] = data[ite].getDistance();
                tableData[i][2] = data[ite].getDuration();
                tableData[i][3] = data[ite].getAltitude();
                ite--;}
        }

        String[] columnNames = {"Date", "Distance Covered (meter)", "Duration (seconds)", "Inclination (meters)"};

        recentRunsTable = new JTable(tableData, columnNames);
        recentRunsTable.setForeground(new java.awt.Color(96, 83, 150));

        jScrollPane2.setViewportView(recentRunsTable);

        javax.swing.GroupLayout recentPanelLayout = new javax.swing.GroupLayout(recentPanel);
        recentPanel.setLayout(recentPanelLayout);
        recentPanelLayout.setHorizontalGroup(
            recentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recentPanelLayout.createSequentialGroup()
                .addGroup(recentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recentPanelLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(JRecentDisplayLabel))
                    .addGroup(recentPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        recentPanelLayout.setVerticalGroup(
            recentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JRecentDisplayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
        );

        mainPanel.add(recentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 540, 150));

        jImportButton.setBackground(new java.awt.Color(96, 83, 150));
        jImportButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jImportButton.setForeground(new java.awt.Color(255, 255, 255));
        jImportButton.setText("Import Data");
        jImportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jImportButtonActionPerformed(evt);
            }
        });
        mainPanel.add(jImportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, -1, -1));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 780, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMouseClicked(MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void mainPanelMousePressed(MouseEvent evt) {//GEN-FIRST:event_mainPanelMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_mainPanelMousePressed

    private void mainPanelMouseDragged(MouseEvent evt) {//GEN-FIRST:event_mainPanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_mainPanelMouseDragged

    //MouseListener for friends panel
    private void jFriendsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFriendsLabelMouseClicked
        JFriendsFrame friendframe = new JFriendsFrame();
        friendframe.setVisible(true);
        friendframe.pack();
        friendframe.setLocationRelativeTo(null);
        friendframe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jFriendsLabelMouseClicked

    //MouseListener for daily challenges
    private void JDailyLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JDailyLabelMouseClicked
        JDailyChallengesFrame dailyFrame = new JDailyChallengesFrame();
        dailyFrame.setVisible(true);
        dailyFrame.pack();
        dailyFrame.setLocationRelativeTo(null);
        dailyFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_JDailyLabelMouseClicked

    //Cant delete use VSCODE!
    private void jFriendsLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFriendsLabel1MouseClicked

    }//GEN-LAST:event_jFriendsLabel1MouseClicked

    //MouseListener to go to run panel
    private void JRunLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JRunLabelMouseClicked
        JRunFrame runframe = new JRunFrame();
        runframe.setVisible(true);
        runframe.pack();
        runframe.setLocationRelativeTo(null);
        runframe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_JRunLabelMouseClicked

    private void jImportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jImportButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(this);
        File csvFile = chooser.getSelectedFile();
        if (csvFile == null)
            return;

        ClassData[] dataSet = CsvImporter.Import(csvFile);

        Singleton.loadedProfile.addRunDatas(dataSet);
        Singleton.dataManager.saveProfile(Singleton.loadedProfile);
        JOptionPane.showMessageDialog(null, "You data has been imported!");
        this.dispose();
        Home h = new Home();
        h.setVisible(true);
        h.pack();
        h.setLocationRelativeTo(null);
        h.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jImportButtonActionPerformed

    int xx, xy;

    //bad idea

    private void onClick(JPanel panel) {
        panel.setBackground(new Color(205, 136, 205));
    }

    private void onLeaveClick(JPanel panel) {
        panel.setBackground(Color.white);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JDailyLabel;
    private javax.swing.JLabel JRecentDisplayLabel;
    private javax.swing.JLabel JRunLabel;
    private javax.swing.JLabel averageIncliLabel;
    private javax.swing.JLabel btn_close;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel distLabel;
    private javax.swing.JLabel distUnit;
    private javax.swing.JLabel incliUnit;
    private javax.swing.JLabel jFriendsLabel;
    private javax.swing.JLabel jFriendsLabel1;
    private javax.swing.JLabel jIconLabel;
    private javax.swing.JButton jImportButton;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable recentRunsTable;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel prettyThing;
    private javax.swing.JPanel recentPanel;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel timeUnit;
    private javax.swing.JLabel title;
    private javax.swing.JLabel incliLabel;
    private javax.swing.JLabel totalDistLabel;
    private javax.swing.JLabel totalTimeLabel;
    // End of variables declaration//GEN-END:variables

}
